spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financial_service
    username: postgres
    password: denis
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
